return {
	Cake = {
		Count = 2,
		Limit = {
			Experience = 1000,
		},
		RoundEpochs = 1,
		RoundLength = 60,
	},
	Coconut = {
		Experience = 15,
	},
	Haybale = {
		Count = 7,
		Experience = 25,
		Requires = {
			Level = 3,
		},
		RoundEpochs = 4,
	},
	Rain = {
		Count = 40,
		Experience = -10,
		Requires = {
			Level = 2,
		},
		RoundEpochs = 2,
		RoundLength = 3,
	},
	Random = Random.new(),
	Shrub = {
		Experience = 5,
		Count = 48,
		RoundLength = 5,
	},
}
